// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfmnaufhdstmflcspoli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmbW5hdWZoZHN0bWZsY3Nwb2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTAyNzIsImV4cCI6MjA3MzQ4NjI3Mn0.hXB1_r1TXk1T96GGcolXMFLvWKO92Mk3Y8pxh9RETFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});